In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline
import seaborn as sns
import warnings 
warnings.filterwarnings( "ignore")

In [2]:
df=pd.read_csv('Downloads/archive (1)/Reviews.csv')

In [3]:
df.head()

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,1303862400,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,1346976000,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,1219017600,"""Delight"" says it all",This is a confection that has been around a fe...
3,4,B000UA0QIQ,A395BORC6FGVXV,Karl,3,3,2,1307923200,Cough Medicine,If you are looking for the secret ingredient i...
4,5,B006K2ZZ7K,A1UQRSCLF8GW1T,"Michael D. Bigham ""M. Wassir""",0,0,5,1350777600,Great taffy,Great taffy at a great price. There was a wid...

In [4]:
df.shape

(568454, 10)

In [5]:
df.describe(include='all').T

,count,unique,top,freq,mean,std,min,25%,50%,75%,max
Id,568454.0,NaN,NaN,NaN,284227.5,164098.679298,1.0,142114.25,284227.5,426340.75,568454.0
ProductId,568454,74258,B007JFMH8M,913,NaN,NaN,NaN,NaN,NaN,NaN,NaN
UserId,568454,256059,A3OXHLG6DIBRW8,448,NaN,NaN,NaN,NaN,NaN,NaN,NaN
ProfileName,568428,218415,"C. F. Hill ""CFH""",451,NaN,NaN,NaN,NaN,NaN,NaN,NaN
HelpfulnessNumerator,568454.0,NaN,NaN,NaN,1.743817,7.636513,0.0,0.0,0.0,2.0,866.0
HelpfulnessDenominator,568454.0,NaN,NaN,NaN,2.22881,8.28974,0.0,0.0,1.0,2.0,923.0
Score,568454.0,NaN,NaN,NaN,4.183199,1.310436,1.0,4.0,5.0,5.0,5.0
Time,568454.0,NaN,NaN,NaN,1296256604.90242,48043312.332415,939340800.0,1271289600.0,1311120000.0,1332720000.0,1351209600.0
Summary,568427,295742,Delicious!,2462,NaN,NaN,NaN,NaN,NaN,NaN,NaN
Text,568454,393579,"This review will make me sound really stupid, ...",199,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 568454 entries, 0 to 568453
Data columns (total 10 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Id                      568454 non-null  int64
 1   ProductId               568454 non-null  object
 2   UserId                  568454 non-null  object
 3   ProfileName             568428 non-null  object
 4   HelpfulnessNumerator    568454 non-null  int64
 5   HelpfulnessDenominator  568454 non-null  int64
 6   Score                   568454 non-null  int64
 7   Time                    568454 non-null  int64
 8   Summary                 568427 non-null  object
 9   Text                    568454 non-null  object
dtypes: int64(5), object(5)
memory usage: 43.4+ MB

In [7]:
# There are some Missing Values
df.isnull().sum()

Id                         0
ProductId                  0
UserId                     0
ProfileName               26
HelpfulnessNumerator       0
HelpfulnessDenominator     0
Score                      0
Time                       0
Summary                   27
Text                       0
dtype: int64

In [8]:
# There is no Duplicated values 
df.duplicated().sum()

0

In [9]:
for cols in df.columns:
    if df[cols].dtype!='object':
        print(cols)
        print(df[cols].value_counts())
        print('\n')

Id
Id
1         1
378972    1
378966    1
378967    1
378968    1
         ..
189480    1
189479    1
189478    1
189477    1
568454    1
Name: count, Length: 568454, dtype: int64


HelpfulnessNumerator
HelpfulnessNumerator
0      303826
1      116467
2       53727
3       29007
4       16963
        ...
446         1
155         1
580         1
355         1
808         1
Name: count, Length: 231, dtype: int64


HelpfulnessDenominator
HelpfulnessDenominator
0      270052
1      112753
2       61482
3       34394
4       22306
        ...
197         1
488         1
383         1
219         1
815         1
Name: count, Length: 234, dtype: int64


Score
Score
5    363122
4     80655
1     52268
3     42640
2     29769
Name: count, dtype: int64


Time
Time
1350345600    1143
1322179200    1088
1322438400    1070
1346889600    1018
1344211200     989
              ...
1095638400       1
1102636800       1
1080259200       1
1087689600       1
1069718400       1
Name: count, Length: 3168, dtype: int64

In [10]:
df[df['ProfileName'].isnull()]

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
10616,10617,B002DHN956,A1LSYR30XW7CFT,NaN,1,2,5,1291680000,Awesome,This is 72 for the price of like 24 at the gro...
25509,25510,B000LKZB4Y,A36BVYD0NT7Z0F,NaN,0,0,5,1314576000,These are the best mints and no aspartame or BHT,I was so shocked to find out that almost all g...
38874,38875,B000AYDGZ2,A36BVYD0NT7Z0F,NaN,2,3,1,1278374400,doesn't anyone care that they are putting BHT ...,I called Kellogg's to see why Special K red be...
47923,47924,B004SRH2B6,A2DEHJJIEAPPBF,NaN,0,0,5,1338940800,Great taste,Enjoy drinking this brand. Tastes as good as ...
49800,49801,B000CRHQN0,A2LYFY32LXQDON,NaN,0,0,2,1282608000,They were melted and the chocolate had turned ...,We love these bars but i won't order them ship...
67077,67078,B0006348H2,A2P0P67Y55SNOX,NaN,1,1,5,1314662400,Wheatgrass,Kitty seems to like this sprinkled on her food...
106550,106551,B001EQ5DG0,A1P500QXEG3IUZ,NaN,0,0,5,1326758400,Finally!,"You cannot find this in the stores anymore, it..."
121819,121820,B006N3I2SK,A34F9B57SYQ5XR,NaN,0,0,5,1335312000,Exactly what I ordered,"Very good coffee, very good price. It can be ..."
125452,125453,B001EO6ESS,A34F9B57SYQ5XR,NaN,0,0,5,1335312000,Exactly what I ordered,"Very good coffee, very good price. It can be ..."
137613,137614,B000CQE3HS,AGT3BYX5P9SLH,NaN,0,0,5,1324684800,awesome,i love them they are amazing I would eat them ...
163191,163192,B000CQID1A,AGT3BYX5P9SLH,NaN,0,0,5,1324684800,awesome,i love them they are amazing I would eat them ...
172462,172463,B001FA1L9I,AC9U70TRGPDGJ,NaN,0,0,5,1289520000,very good,came in proper packaging. Have loved British ...
211846,211847,B000CNB4LE,A2DEHJJIEAPPBF,NaN,0,0,5,1338940800,Great taste,Enjoy drinking this brand. Tastes as good as ...
268648,268649,B004SRFYMK,A2DEHJJIEAPPBF,NaN,0,0,5,1338940800,Great taste,Enjoy drinking this brand. Tastes as good as ...
297275,297276,B007OXJM6E,A29D7XVSBCLFLD,NaN,0,0,1,1325203200,Burnt,The last SEVERAL time we bought this it tasted...
306751,306752,B000RI1W8E,AGT3BYX5P9SLH,NaN,0,0,5,1324684800,awesome,i love them they are amazing I would eat them ...
331647,331648,B0000GHNTU,A1PZJLGDQSLZWE,NaN,0,0,4,1335139200,Great product - Lousy Customer Service,This sauce is excellent. Medium hot with smoky...
358674,358675,B003CIBPN8,A2DEHJJIEAPPBF,NaN,0,0,5,1338940800,Great taste,Enjoy drinking this brand. Tastes as good as ...
431598,431599,B000W5P0KI,A36BVYD0NT7Z0F,NaN,13,21,1,1298937600,WARNING: Please read before feeding,WARNING: I use to feed my dogs Orijen 75% pro...
440825,440826,B008LFAS08,AC0E8TXIYABB5,NaN,1,1,5,1350432000,The perfect grinder for dog and cat food!,this grinder is super easy to assemble and ope...
461668,461669,B008K9TJDM,A34F9B57SYQ5XR,NaN,0,0,5,1335312000,Exactly what I ordered,"Very good coffee, very good price. It can be ..."
490412,490413,B000CQE3IC,AGT3BYX5P9SLH,NaN,0,0,5,1324684800,awesome,i love them they are amazing I would eat them ...
491728,491729,B004772PJQ,A29D7XVSBCLFLD,NaN,0,0,1,1325203200,Burnt,The last SEVERAL time we bought this it tasted...
515436,515437,B004S04X4W,A2H7605OSHVIQ5,NaN,0,0,5,1348704000,"Hormel Roast Beef Hash, 15-Ounce",I've been buying this in the grocery stores fr...
517676,517677,B008CIS05O,A1VIUQE908L3M3,NaN,0,0,5,1349308800,Classis Dentyne Spearmint Gum,It is just what I wanted and as I remembered i...
560446,560447,B000CQID1K,AGT3BYX5P9SLH,NaN,0,0,5,1324684800,awesome,i love them they are amazing I would eat them ...

In [11]:
df[df['Summary'].isnull()]

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
33958,33959,B00412W76S,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
40548,40549,B00020HHRW,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
101106,101107,B0014B0HWK,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
102979,102980,B000FVDWU4,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
117515,117516,B0016B7Z32,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
155712,155713,B0009VO58S,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
178290,178291,B00073IVAQ,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
198474,198475,B000FVBYCW,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
212691,212692,B00020HHAO,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
237565,237566,B000ELGPAO,A15AMT9T9A1309,Film-Friend,1,1,3,1328572800,NaN,This is a cool system only problem is that the...
293906,293907,B00020HHM2,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
299495,299496,B00142BX68,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
300961,300962,B000VJYTZM,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
333556,333557,B00188S3PM,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
352043,352044,B000M0F58U,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
357215,357216,B0006I5M2M,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
357814,357815,B001GCTTRQ,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
360782,360783,B00020HHHC,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
379473,379474,B007RLRCLK,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
380558,380559,B00014DXCC,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
381313,381314,B00020HHK4,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
386283,386284,B00073JVFU,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
392529,392530,B001H9XOEW,A22R17YPXEULEZ,Liz Wong,0,0,3,1334534400,NaN,I like the product and tried it before I pucha...
484367,484368,B00020HHGS,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
486640,486641,B0014AUJII,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
503260,503261,B00020HHE0,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...
530716,530717,B0014ATRV8,A3TJPSWY2HE4BS,"S. Layton ""homeschool blogger""",1,24,2,1173312000,NaN,I only used two maybe three tea bags and got p...

In [12]:
# Lets Clean som data

In [13]:
# Since our Time coloum is in Unix Timestamp Lets Convert it into Date Time formate

In [14]:
df['Time'] = pd.to_datetime(df['Time'], unit='s')

In [15]:
df.head(3)

,Id,ProductId,UserId,ProfileName,HelpfulnessNumerator,HelpfulnessDenominator,Score,Time,Summary,Text
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,2011-04-27,Good Quality Dog Food,I have bought several of the Vitality canned d...
1,2,B00813GRG4,A1D87F6ZCVE5NK,dll pa,0,0,1,2012-09-07,Not as Advertised,Product arrived labeled as Jumbo Salted Peanut...
2,3,B000LQOCH0,ABXLMWJIXXAIN,"Natalia Corres ""Natalia Corres""",1,1,4,2008-08-18,"""Delight"" says it all",This is a confection that has been around a fe...

## Data Cleaning EDA

In [17]:
# Now lets Rename some column names

In [18]:
df.rename(columns={'HelpfulnessNumerator': 'Helpful_Votes'}, inplace=True)
df.rename(columns={'HelpfulnessDenominator': 'Total_Votes'}, inplace=True)
df.rename(columns={'Score':'Ratings'},inplace=True)
df.rename(columns={'Text':'Text_Review'},inplace=True)

In [19]:
df.head(1)

,Id,ProductId,UserId,ProfileName,Helpful_Votes,Total_Votes,Ratings,Time,Summary,Text_Review
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,2011-04-27,Good Quality Dog Food,I have bought several of the Vitality canned d...

In [20]:
df.columns

Index(['Id', 'ProductId', 'UserId', 'ProfileName', 'Helpful_Votes',
       'Total_Votes', 'Ratings', 'Time', 'Summary', 'Text_Review'],
      dtype='object')

In [21]:
df.rename(columns={'ProductId':'Product_ID'},inplace=True)
df.rename(columns={'UserId':'User_ID'},inplace=True)
df.rename(columns={'ProfileName':'Profile_Name'},inplace=True)

In [22]:
# There Are some null values in Profile Name and Summary Beacouse they are not so usefull for our Sentimental Analysis we replace them with 'Unknown' & 'Text'

In [23]:
# Fill ProfileName with "Unknown"
df['Profile_Name'].fillna('Unknown', inplace=True)

# Fill Summary with Text (if missing)
df['Summary'].fillna('No_Summary', inplace=True)

In [24]:
# Lets  Remove Unnecessary Characters & Lowercase Text
# Lets import Regular expression

In [25]:
import re

In [26]:
def clean_text(text):
    text = text.lower()  # Convert to lowercase
    text = re.sub(r'\d+', '', text)  # Remove numbers
    text = re.sub(r'[^\w\s]', '', text)  # Remove punctuation
    text = re.sub(r'\s+', ' ', text).strip()  # Remove extra spaces
    return text

In [27]:
df['Cleaned_Text'] = df['Text_Review'].apply(clean_text)

In [28]:
# Convert Text into Numerical Data (Feature Extraction)Since models can’t understand raw text, we need to convert it into vectors.

In [29]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [30]:
vectorizer = TfidfVectorizer(max_features=5000)  # Limit to 5000 most important words
X = vectorizer.fit_transform(df['Cleaned_Text'])  # Transform text into numerical vectors

In [31]:
correlation = df.corr(numeric_only=True)
sns.heatmap(correlation,annot=True,fmt='0.2f',cmap='Blues');

In [32]:
# Splitting the reviews so that it make easy to plot and understand easily
# if reviwe is >=4 its'Positive'
# if review is ==3 its 'Neutral'
# if review is <3 its 'Negative'
df['Sentiment'] = df['Ratings'].apply(lambda x: 2 if x >= 4 else (1 if x == 3 else 0))

In [33]:
plt.figure(figsize=(7, 5))
sns.countplot(x=df['Sentiment'], palette=['red', 'orange', 'green'])
plt.xticks(ticks=[0, 1, 2], labels=['Negative', 'Neutral', 'Positive'])
plt.title("Sentiment Distribution");

In [34]:
plt.figure(figsize=(7, 5))
sns.countplot(x=df['Ratings'], palette='viridis')
plt.title("Distribution of Ratings (1-5)")
plt.xlabel("Ratings")
plt.ylabel("Count");

In [35]:
# Hear we are checking do longer reviews gets more helpfull votes 
df['Review_Length'] = df['Text_Review'].apply(lambda x: len(str(x).split()))

In [36]:
plt.figure(figsize=(8, 5))
sns.scatterplot(x=df['Review_Length'], y=df['Helpful_Votes'], alpha=0.5)
plt.title("Helpfulness vs. Review Length")
plt.xlabel("Review Length (Word Count)")
plt.ylabel("Helpful Votes");

### 1. Longer reviews tend to get more helpful votes (but not always).
### 2. There is no strong correlation (some short reviews get high votes too).

In [38]:
# Checking for Outliers 
plt.figure(figsize=(15,5))
plt.xticks(rotation=60)
sns.boxplot(data=df);

### In this case there is no such extream outliers to treat we can ignore it

In [40]:
# Extract Year from Time column so that we can plot to see are negative reviews increasing over time?

df['Year'] = df['Time'].dt.year

In [41]:
plt.figure(figsize=(10, 5))
sns.lineplot(data=df.groupby('Year')['Sentiment'].mean())
plt.title("Sentiment Trend Over Time")
plt.ylabel("Average Sentiment Score");

### 1.Product Quality Issues → If the sentiment is dropping, it may indicate declining quality.
### 2. Changing User Behavior → Customers may have become more critical over time.
### 3. More Diverse Products → Some products may have attracted more negative reviews.
### 4. Dataset Imbalance → If the dataset has more recent negative reviews, it could impact the trend.

In [43]:
# Generate WordCloud for Positive & Negative Reviews so that we can Find the most frequently used words in reviews.
positive_reviews = " ".join(df[df['Sentiment'] == 2]['Text_Review'])
negative_reviews = " ".join(df[df['Sentiment'] == 0]['Text_Review'])

In [44]:
!pip install WordCloud

Collecting WordCloud
  Downloading wordcloud-1.9.4-cp312-cp312-win_amd64.whl.metadata (3.5 kB)
Requirement already satisfied: numpy>=1.6.1 in c:\users\prajwal s\anaconda3\lib\site-packages (from WordCloud) (1.26.4)
Requirement already satisfied: pillow in c:\users\prajwal s\anaconda3\lib\site-packages (from WordCloud) (10.4.0)
Requirement already satisfied: matplotlib in c:\users\prajwal s\anaconda3\lib\site-packages (from WordCloud) (3.9.2)
Requirement already satisfied: contourpy>=1.0.1 in c:\users\prajwal s\anaconda3\lib\site-packages (from matplotlib->WordCloud) (1.2.0)
Requirement already satisfied: cycler>=0.10 in c:\users\prajwal s\anaconda3\lib\site-packages (from matplotlib->WordCloud) (0.11.0)
Requirement already satisfied: fonttools>=4.22.0 in c:\users\prajwal s\anaconda3\lib\site-packages (from matplotlib->WordCloud) (4.51.0)
Requirement already satisfied: kiwisolver>=1.3.1 in c:\users\prajwal s\anaconda3\lib\site-packages (from matplotlib->WordCloud) (1.4.4)
Requirement already satisfied: packaging>=20.0 in c:\users\prajwal s\anaconda3\lib\site-packages (from matplotlib->WordCloud) (24.1)
Requirement already satisfied: pyparsing>=2.3.1 in c:\users\prajwal s\anaconda3\lib\site-packages (from matplotlib->WordCloud) (3.1.2)
Requirement already satisfied: python-dateutil>=2.7 in c:\users\prajwal s\anaconda3\lib\site-packages (from matplotlib->WordCloud) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in c:\users\prajwal s\anaconda3\lib\site-packages (from python-dateutil>=2.7->matplotlib->WordCloud) (1.16.0)
Downloading wordcloud-1.9.4-cp312-cp312-win_amd64.whl (301 kB)
Installing collected packages: WordCloud
Successfully installed WordCloud-1.9.4

In [45]:
from wordcloud import WordCloud

In [46]:
# This is positive Reviews
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 1)
plt.imshow(WordCloud(width=400, height=200, background_color='white').generate(positive_reviews))
plt.title("Positive Reviews Word Cloud")
plt.axis('off');

In [47]:
# This is Negative reviews
plt.figure(figsize=(12, 5))
plt.subplot(1, 2, 2)
plt.imshow(WordCloud(width=400, height=200, background_color='black').generate(negative_reviews))
plt.title("Negative Reviews Word Cloud")
plt.axis('off');

In [48]:
# Before building a model lets drop some unnecessary column which are not so usfull for further 
# So we are droping some column as  we  are doing sentimental Analysis

In [49]:
df.head(1)

,Id,Product_ID,User_ID,Profile_Name,Helpful_Votes,Total_Votes,Ratings,Time,Summary,Text_Review,Cleaned_Text,Sentiment,Review_Length,Year
0,1,B001E4KFG0,A3SGXH7AUHU8GW,delmartian,1,1,5,2011-04-27,Good Quality Dog Food,I have bought several of the Vitality canned d...,i have bought several of the vitality canned d...,2,48,2011

In [50]:
df.drop(['Id','Year','User_ID','Profile_Name','Time','Summary','Text_Review'],axis=1,inplace=True)

In [51]:
# And the produc id is in string formate we must convert it into float or an int so we are using LabelEncoder

In [52]:
from sklearn.preprocessing import LabelEncoder

In [53]:
df

,Product_ID,Helpful_Votes,Total_Votes,Ratings,Cleaned_Text,Sentiment,Review_Length
0,B001E4KFG0,1,1,5,i have bought several of the vitality canned d...,2,48
1,B00813GRG4,0,0,1,product arrived labeled as jumbo salted peanut...,0,31
2,B000LQOCH0,1,1,4,this is a confection that has been around a fe...,2,94
3,B000UA0QIQ,3,3,2,if you are looking for the secret ingredient i...,0,41
4,B006K2ZZ7K,0,0,5,great taffy at a great price there was a wide ...,2,27
...,...,...,...,...,...,...,...
568449,B001EO7N10,0,0,5,great for sesame chickenthis is a good if not ...,2,26
568450,B003S1WTCU,0,0,2,im disappointed with the flavor the chocolate ...,0,46
568451,B004I613EE,2,2,5,these stars are small so you can give of those...,2,66
568452,B004I613EE,1,1,5,these are the best treats for training and rew...,2,35
568453,B001LR2CU2,0,0,5,i am very satisfied product is as advertised i...,2,21

In [54]:
# Encode Product_ID as numeric values
encoder = LabelEncoder()
df['Product_ID'] = encoder.fit_transform(df['Product_ID'])

In [55]:
# Since machine learning models cannot understand raw text, we must convert Cleaned_Text into numerical vectors using TF-IDF.

In [56]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [57]:
vectorizer = TfidfVectorizer(max_features=5000)

In [58]:
Amazon= vectorizer.fit_transform(df['Cleaned_Text'])

In [59]:
from scipy.sparse import hstack

In [60]:
# Drop raw text since we converted it
df = df.drop(columns=['Cleaned_Text'])

In [61]:
sparse = hstack([df.values, Amazon])  # Combine structured data with TF-IDF

In [62]:
Amazon.shape

(568454, 5000)

In [63]:
# Now lets Split our data to build a model and import Test Train split

In [64]:
from sklearn.model_selection import train_test_split

In [65]:
x=df.drop('Sentiment',axis=1)
y=df['Sentiment']

In [66]:
x.head(2)

   Product_ID  Helpful_Votes  Total_Votes  Ratings  Review_Length
0       27619              1            1        5             48
1       72383              0            0        1             31

In [67]:
y.head()

0    2
1    0
2    2
3    0
4    2
Name: Sentiment, dtype: int64

In [68]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=42)

In [69]:
x_train.shape

(397917, 5)

In [70]:
x_test.shape

(170537, 5)

In [71]:
# Since we are starting with Logistic Regression lets build a model

In [72]:
from sklearn.linear_model import LogisticRegression

In [73]:
Model=LogisticRegression(class_weight={0:2, 1:4, 2:1}, random_state=42)

In [74]:
Model.fit(x_train,y_train)

LogisticRegression(class_weight={0: 2, 1: 4, 2: 1}, random_state=42)

In [75]:
Model.score(x_train,y_train)

0.8671004254656122

In [76]:
Model.score(x_test,y_test)

0.8666447750341568

### Since our model is low bias and low Varience its Genralized Fitting

In [78]:
# Hear we are importing the classification report and confusion matrix 
# classification report--The classification report provides detailed metrics for each class in the dataset
# confusion matrix--it is a table that summarizes the performance of a classification model by comparing predicted labels with true labels.
from sklearn.metrics import confusion_matrix,classification_report

In [79]:
y_train_predict=Model.predict(x_train)
y_test_predict=Model.predict(x_test)

In [80]:
# Now lets create a Heat map to check the performance of a classification model by comparing predicted labels with true labels 
sns.heatmap(confusion_matrix(y_train,y_train_predict),annot=True,fmt='g',cmap='Blues');

In [81]:
# Now lets print classification report so it provides detailed metrics for each class in the dataset
print(classification_report(y_train,y_train_predict))

              precision    recall  f1-score   support

           0       0.94      0.62      0.75     57759
           1       0.32      0.31      0.32     29790
           2       0.91      0.97      0.93    310368

    accuracy                           0.87    397917
   macro avg       0.72      0.63      0.67    397917
weighted avg       0.87      0.87      0.86    397917

In [82]:
print(classification_report (y_test,y_test_predict))

              precision    recall  f1-score   support

           0       0.94      0.62      0.75     24278
           1       0.32      0.30      0.31     12850
           2       0.90      0.97      0.93    133409

    accuracy                           0.87    170537
   macro avg       0.72      0.63      0.66    170537
weighted avg       0.87      0.87      0.86    170537

### Since class 1 was showing 0 we have used classbalance in the model